# Generated by Django 4.1.7 on 2023-02-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=999)),
                ('modelNO', models.CharField(max_length=999)),
                ('Enable', models.BooleanField(default=True)),
                ('index', models.BooleanField()),
                ('position', models.IntegerField(blank=True, null=True, unique=True)),
                ('description', models.TextField(max_length=12000)),
                ('document', models.FileField(upload_to='document/')),
                ('note', models.CharField(blank=True, max_length=999, null=True)),
                ('htmlcode', models.TextField(blank=True, max_length=12000, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
