# Generated by Django 4.1.7 on 2023-02-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
    ]
